# Generated by Django 4.0.3 on 2022-04-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictinfo',
            name='predicted_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
